# .github/workflows/ci-scripts-build.yml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

name: YOKOGAWA_DAS

# Trigger on pushes and PRs to any branch
on:
  push:
    paths-ignore:
      - 'docs/*'
      - '**/*.html'
      - '**/*.md'
    branches:
      - master
  pull_request:

env:
  SETUP_PATH: .github/workflows:.ci
  APT: re2c

jobs:
  build-base:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CMP: ${{ matrix.cmp }}
      BCFG: ${{ matrix.configuration }}
      SET: ${{ matrix.set }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            cmp: gcc
            configuration: default
            set: linux-stable-3_15
            name: "Linux-stable 3.15"

          - os: ubuntu-24.04
            cmp: gcc
            configuration: default
            set: linux-stable-7_0
            name: "Linux-stable 7.0"

          - os: ubuntu-24.04
            cmp: gcc
            configuration: default
            set: linux-master
            name: "Linux-master 7.0"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Automatic core dumper analysis
      uses: mdavidsaver/ci-core-dumper@master
    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare
    - name: Enable IOC builds for master
      run: echo "BUILD_IOCS = YES" >> configure/CONFIG_SITE.local
      if: ${{ !contains(matrix.set, 'stable') }}
    - name: Build main module
      run: python .ci/cue.py build
    - name: Run main module tests
      run: python .ci/cue.py -T 15M test
    - name: Upload tapfiles Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tapfiles ${{ matrix.name }}
        path: '**/O.*/*.tap'
    - name: Collect and show test results
      run: python .ci/cue.py test-results
